DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS USER2;


CREATE TABLE USER2 (
    userid IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL,
    password VARCHAR(32) NOT NULL
);

CREATE TABLE ITEM (
    itemid IDENTITY PRIMARY KEY,
    userid INT NOT NULL,
    name VARCHAR(32) NOT NULL,
    description VARCHAR(512) NOT NULL,

    CONSTRAINT FK_ITEM_USER2
    FOREIGN KEY (userid)
    REFERENCES USER2(userid)

);
